backend:
    name: git-gateway
    branch: master

media_folder: static/assets
public_folder: assets

media_folder_relative: true

publish_mode: editorial_workflow

collections:
    - name: designers
      label: Designer
      folder: contents/designers
      create: true
      fields:
          - { label: 'Nome', name: 'name', widget: 'string' }
          - label: 'Lavoro'
            name: 'job'
            widget: 'object'
            fields:
                - { label: 'Tipologia', name: 'type', widget: 'string' }
                - {
                      label: 'Azienda',
                      name: 'company',
                      widget: 'string',
                      default: '-',
                  }
          - label: 'Ambito'
            name: 'jobFields'
            widget: 'select'
            multiple: true
            options: ['Brand design', 'Editorial design']
          - label: 'Basato a'
            name: 'based'
            widget: 'object'
            fields:
                - { label: 'Nazione', name: 'country', widget: 'string' }
                - { label: 'Città', name: 'city', widget: 'string' }
          - {
                label: 'Premi',
                name: 'awards',
                widget: 'boolean',
                default: false,
            }
          - label: 'Data di aggiunta'
            name: 'date'
            widget: 'date'
            default: ''
            format: 'YYYY-MM-DD'
          - label: 'Immagine'
            name: 'img'
            widget: 'image'
          - { label: 'Corpo', name: 'body', widget: 'markdown' }

    - name: projects
      label: Progetti
      folder: contents/projects
      create: true
      fields:
          - { label: 'Titolo', name: 'name', widget: 'string' }
          - { label: 'Committente', name: 'client', widget: 'string' }
          - {
                label: 'Anno di consegna del progetto',
                name: 'year',
                widget: 'number',
                valueType: 'int',
            }
          - label: 'Designer'
            name: 'designer'
            widget: 'relation'
            collection: 'designers'
            searchFields: ['name']
            valueField: 'name'
            multiple: true
          - label: 'Anteprima'
            name: preview
            widget: 'image'
            allow_multiple: false
          - label: 'Immagini'
            name: 'images'
            widget: 'list'
            field: { label: Image, name: image, widget: image }
          - label: 'Data di aggiunta'
            name: 'date'
            widget: 'date'
            default: ''
            format: 'YYYY-MM-DD'
          - { label: 'Corpo', name: 'body', widget: 'markdown' }
    - name: extras
      label: Extras
      folder: contents/extras
      create: true
      fields:
          - { label: 'Titolo', name: 'name', widget: 'string' }
          - {
                label: 'Tipo di contenuto',
                name: 'content_type',
                widget: 'string',
            }
          - label: 'Designer'
            name: 'designer'
            widget: 'relation'
            collection: 'designers'
            searchFields: ['name']
            valueField: 'name'
            multiple: true
          - label: 'Data di aggiunta'
            name: 'date'
            widget: 'date'
            default: ''
            format: 'YYYY-MM-DD'
          - { label: 'Corpo', name: 'body', widget: 'markdown' }
